FROM node:20-alpine

WORKDIR /app

# Copiar manifiestos de dependencias
COPY package*.json ./

# Instalar dependencias del proyecto
RUN npm install

# Copiar el resto del código fuente
COPY . .

# Exponer el puerto de desarrollo
EXPOSE 4200

# Comando predeterminado de inicio
CMD ["npx", "ng", "serve", "--host", "0.0.0.0", "--port", "4200"]