# Generated by Django 6.0.5 on 2026-09-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comanda',
            options={},
        ),
        migrations.RemoveField(
            model_name='comanda',
            name='actualizado_en',
        ),
        migrations.RemoveField(
            model_name='comanda',
            name='notas',
        ),
        migrations.AddField(
            model_name='comanda',
            name='numero_pedido',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='comanda',
            name='sector',
            field=models.CharField(choices=[('COCINA', 'Cocina'), ('BARRA', 'Barra')], default='COCINA', max_length=20),
        ),
        migrations.AddField(
            model_name='comanda',
            name='tiempo_espera',
            field=models.CharField(default='10 min', max_length=50),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PREPARACION', 'En Preparación'), ('LISTO', 'Listo')], default='PENDIENTE', max_length=20),
        ),
    ]
