# Generated by Django 6.0.5 on 2026-09-27 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0002_alter_comanda_options_remove_comanda_actualizado_en_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comanda',
        ),
    ]
