# Generated by Django 6.0.5 on 2026-09-28 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado_barra',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PREPARACION', 'Preparación'), ('LISTO', 'Listo'), ('ENTREGADO', 'Entregado'), ('CERRADO', 'Cerrado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado_cocina',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PREPARACION', 'Preparación'), ('LISTO', 'Listo'), ('ENTREGADO', 'Entregado'), ('CERRADO', 'Cerrado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20),
        ),
    ]
