# Generated by Django 6.0.5 on 2026-09-29 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CierreCaja',
            fields=[
                ('id_cierre', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateField()),
                ('monto_efectivo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monto_tarjeta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monto_transferencia', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monto_otro', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_cobrado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_rendido', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('diferencia', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cajero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cierres', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cierre de caja',
                'verbose_name_plural': 'Cierres de caja',
                'db_table': 'cierres_caja',
                'constraints': [models.UniqueConstraint(fields=('fecha_cierre',), name='unico_cierre_por_dia')],
            },
        ),
    ]
